version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  prediction-service:
    build: .
    container_name: prediction_service
    command: python Services/Prediction_Service.py
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - PYTHONPATH=/app
      - PROMETHEUS_PORT=8000
      - PROMETHEUS_HOST=0.0.0.0
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  prometheus:
      image: prom/prometheus:v2.45.0
      container_name: prometheus
      restart: always
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml  
      healthcheck:
        test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
        interval: 10s
        timeout: 5s
        retries: 5
  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      restart: always
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      depends_on:
        prometheus:
          condition: service_healthy
      volumes:
        - grafana-storage:/var/lib/grafana
  logging-service:
    build: .
    container_name: logging_service
    command: python Services/Logging_Service.py
    ports:
      - "8001:8000"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - PYTHONPATH=/app
      - PROMETHEUS_PORT=8000
      - PROMETHEUS_HOST=0.0.0.0
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  publisher-service:
    build: .
    container_name: publisher_service
    command: python Services/Service_Publisher.py
    ports:
      - "8002:8000"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PROMETHEUS_PORT=8000
      - PROMETHEUS_HOST=0.0.0.0
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
volumes:
  grafana-storage: